MODEL:
  META_ARCHITECTURE: "ATSS"
  #WEIGHTS: "pretrained/atss_1_class.pth"
  # WEIGHTS: "/sda/public/auto_cut/dyhead_swint_atss_fpn_2x_ms.pth"
  WEIGHTS: "../cut_question.pth"
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]
  BACKBONE:
    NAME: "build_retinanet_swint_fpn_dyhead_backbone"
  SWINT:
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
  DYHEAD:
    NUM_CONVS: 6
    CHANNELS: 256
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x*2,] for x in [32, 64, 128, 256, 512 ]]"]
    ASPECT_RATIOS: [0.5,1.0]
    OFFSET: 0.5
  ATSS:
    NUM_CONVS: 0
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("cut_ques_train",)
  TEST: ("cut_ques_val",)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.05
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  OPTIMIZER: "ADAMW"
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
